package com.upscprep.app

import android.content.Context
import android.graphics.Bitmap
import android.net.Uri
import androidx.activity.compose.rememberLauncherForActivityResult
import androidx.activity.result.contract.ActivityResultContracts
import androidx.compose.foundation.layout.*
import androidx.compose.foundation.rememberScrollState
import androidx.compose.foundation.verticalScroll
import androidx.compose.material3.*
import androidx.compose.runtime.*
import androidx.compose.ui.Modifier
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.unit.dp
import java.io.ByteArrayOutputStream

object DemoLocalState {
    var optional by mutableStateOf("")
    val notes = mutableStateListOf<String>()
    val wrong = mutableStateListOf<String>()
}

@Composable fun DemoAiTeacherScreen(back:()->Unit){var mode by remember{mutableStateOf("Prelims")};var q by remember{mutableStateOf("")};var answer by remember{mutableStateOf("")};Column(Modifier.fillMaxSize().verticalScroll(rememberScrollState()).padding(20.dp)){TextButton(onClick=back){Text("← AI Teacher")};Text("AI Teacher",style=MaterialTheme.typography.headlineSmall,fontWeight=FontWeight.Bold);Text("TEST MODE • current facts invent नहीं किए जाते");Row{listOf("Prelims","Mains","Revision").forEach{TextButton(onClick={mode=it}){Text(if(mode==it)"✓ $it" else it)}}};OutlinedTextField(q,{q=it},label={Text("अपना सवाल लिखें")},modifier=Modifier.fillMaxWidth());Button(enabled=q.isNotBlank(),onClick={answer=when(mode){"Mains"->"उत्तर-ढांचा: demand पहचानें → परिचय → मुख्य dimensions → balanced analysis → conclusion. Current factual claims production verified knowledge gate से ही आएँगे।";"Revision"->"Quick revision: topic को definition, core concepts, common traps और recall points में revise करें।";else->"Prelims approach: concept स्पष्ट करें, keywords पहचानें और elimination logic लगाएँ। Current facts local demo में उपलब्ध नहीं हैं।"}},modifier=Modifier.fillMaxWidth().padding(top=10.dp)){Text("पूछें")};if(answer.isNotBlank())Card(Modifier.fillMaxWidth().padding(top=12.dp)){Text(answer,Modifier.padding(16.dp))}}}

@Composable fun DemoMockScreen(back:()->Unit){val completed=DemoTestData.completed.filter{it.startsWith("prelims|")};var started by remember{mutableStateOf(false)};var selected by remember{mutableStateOf<Int?>(null)};var submitted by remember{mutableStateOf(false)};Column(Modifier.fillMaxSize().verticalScroll(rememberScrollState()).padding(20.dp)){TextButton(onClick=back){Text("← PRELIMS")};Text("Combined Mock",style=MaterialTheme.typography.headlineSmall,fontWeight=FontWeight.Bold);Text("TEST MODE • केवल completed topics • wrong answer = −1/3");if(completed.isEmpty())Text("पहले Prelims syllabus में कम-से-कम एक topic Complete करें।",Modifier.padding(top=16.dp))else if(!started)Button(onClick={started=true},Modifier.fillMaxWidth().padding(top=16.dp)){Text("Mock शुरू करें") }else{Text("Q1. Completed topics पर test-flow question",Modifier.padding(vertical=12.dp));listOf("Option A","Option B","Option C","Option D").forEachIndexed{i,x->Row{RadioButton(selected==i,{selected=i});Text(x,Modifier.padding(top=12.dp))}};Button(onClick={submitted=true},enabled=selected!=null,modifier=Modifier.fillMaxWidth()){Text("Submit")};if(submitted){val score=if(selected==0)2.0 else -2.0/3.0;Text("Test score: %.2f • Negative marking applied".format(score),fontWeight=FontWeight.Bold,modifier=Modifier.padding(top=12.dp));if(selected!=0&&!DemoLocalState.wrong.contains("Combined Mock Q1"))DemoLocalState.wrong.add("Combined Mock Q1")}}}}

@Composable fun DemoOptionalScreen(back:()->Unit){val subjects=listOf("Anthropology","Geography","History","Political Science & IR","Public Administration","Sociology","Philosophy","Psychology","Economics","Law","Mathematics");Column(Modifier.fillMaxSize().verticalScroll(rememberScrollState()).padding(20.dp)){TextButton(onClick=back){Text("← OPTIONAL")};Text("Optional",style=MaterialTheme.typography.headlineSmall,fontWeight=FontWeight.Bold);Text("TEST MODE • एक समय में exactly one optional");subjects.forEach{s->Card(onClick={DemoLocalState.optional=s},Modifier.fillMaxWidth().padding(vertical=4.dp)){Row(Modifier.padding(14.dp)){RadioButton(DemoLocalState.optional==s,{DemoLocalState.optional=s});Column{Text(s,fontWeight=FontWeight.Bold);Text("Paper I • 250 marks | Paper II • 250 marks")}}}};if(DemoLocalState.optional.isNotBlank())Text("Selected: ${DemoLocalState.optional} ✓",fontWeight=FontWeight.Bold,modifier=Modifier.padding(top=10.dp));Text("Full official optional syllabus/PYQ production official-source registry से आएगा; demo कोई syllabus invent नहीं करता।",style=MaterialTheme.typography.labelMedium,modifier=Modifier.padding(top=8.dp))}}

@Composable fun DemoNotesScreen(context:Context,back:()->Unit){var exam by remember{mutableStateOf("Prelims")};var subject by remember{mutableStateOf("")};var topic by remember{mutableStateOf("")};var subtopic by remember{mutableStateOf("")};var picked by remember{mutableStateOf("")};val file=rememberLauncherForActivityResult(ActivityResultContracts.OpenDocument()){u:Uri?->picked=u?.lastPathSegment?:""};val photo=rememberLauncherForActivityResult(ActivityResultContracts.GetContent()){u:Uri?->picked=u?.lastPathSegment?:""};val camera=rememberLauncherForActivityResult(ActivityResultContracts.TakePicturePreview()){b:Bitmap?->if(b!=null){val o=ByteArrayOutputStream();b.compress(Bitmap.CompressFormat.JPEG,85,o);picked="camera-photo.jpg"}};Column(Modifier.fillMaxSize().verticalScroll(rememberScrollState()).padding(20.dp)){TextButton(onClick=back){Text("← CLASS NOTES")};Text("Class Notes",style=MaterialTheme.typography.headlineSmall,fontWeight=FontWeight.Bold);Row{listOf("Prelims","Mains","Optional").forEach{TextButton(onClick={exam=it}){Text(if(exam==it)"✓ $it" else it)}}};OutlinedTextField(subject,{subject=it},label={Text("Subject")},modifier=Modifier.fillMaxWidth());OutlinedTextField(topic,{topic=it},label={Text("Topic")},modifier=Modifier.fillMaxWidth());OutlinedTextField(subtopic,{subtopic=it},label={Text("Subtopic")},modifier=Modifier.fillMaxWidth());Row(Modifier.fillMaxWidth(),horizontalArrangement=Arrangement.spacedBy(6.dp)){OutlinedButton({file.launch(arrayOf("application/pdf","image/*"))},Modifier.weight(1f)){Text("PDF")};OutlinedButton({photo.launch("image/*")},Modifier.weight(1f)){Text("Photo")};OutlinedButton({camera.launch(null)},Modifier.weight(1f)){Text("Camera")}};if(picked.isNotBlank())Text("Selected: $picked");Button(enabled=subject.isNotBlank()&&topic.isNotBlank()&&picked.isNotBlank(),onClick={DemoLocalState.notes.add("$exam • $subject • $topic • $subtopic • $picked");picked=""},modifier=Modifier.fillMaxWidth().padding(top=8.dp)){Text("Note Save करें")};DemoLocalState.notes.forEach{Card(Modifier.fillMaxWidth().padding(top=6.dp)){Text(it,Modifier.padding(12.dp))}}}}

@Composable fun DemoOfficialOnlyScreen(title:String,detail:String,back:()->Unit){Column(Modifier.fillMaxSize().padding(20.dp)){TextButton(onClick=back){Text("← Back")};Text(title,style=MaterialTheme.typography.headlineSmall,fontWeight=FontWeight.Bold);Card(Modifier.fillMaxWidth().padding(top=14.dp)){Column(Modifier.padding(18.dp)){Text("TEST MODE",fontWeight=FontWeight.Bold);Text(detail,Modifier.padding(top=8.dp));Text("गलत/बनावटी data दिखाने के बजाय live verified backend मिलने तक यह हिस्सा intentionally official-only है।",style=MaterialTheme.typography.labelMedium,modifier=Modifier.padding(top=8.dp))}}}}

@Composable fun DemoWrongScreen(back:()->Unit){Column(Modifier.fillMaxSize().padding(20.dp)){TextButton(onClick=back){Text("← WRONG QUESTIONS")};Text("Wrong Questions",style=MaterialTheme.typography.headlineSmall,fontWeight=FontWeight.Bold);if(DemoLocalState.wrong.isEmpty())Text("Mock में गलत हुए questions यहाँ अपने-आप जुड़ेंगे।",Modifier.padding(top=14.dp));DemoLocalState.wrong.forEach{Card(Modifier.fillMaxWidth().padding(top=6.dp)){Text(it,Modifier.padding(16.dp))}}}}
@Composable fun DemoRevisionScreen(back:()->Unit){val done=DemoTestData.completed.toList();Column(Modifier.fillMaxSize().verticalScroll(rememberScrollState()).padding(20.dp)){TextButton(onClick=back){Text("← REVISION")};Text("Revision",style=MaterialTheme.typography.headlineSmall,fontWeight=FontWeight.Bold);Text("Completed topics: ${done.size} • Wrong questions: ${DemoLocalState.wrong.size}",Modifier.padding(vertical=12.dp));done.forEach{Card(Modifier.fillMaxWidth().padding(top=5.dp)){Text(it.substringAfterLast('|'),Modifier.padding(14.dp))}}}}

@Composable fun DemoMainsPaperScreen(back:()->Unit){Column(Modifier.fillMaxSize().verticalScroll(rememberScrollState()).padding(20.dp)){TextButton(onClick=back){Text("← MAINS")};Text("Mains Test Paper",style=MaterialTheme.typography.headlineSmall,fontWeight=FontWeight.Bold);Text("TEST MODE • QCA-style structural preview");(1..20).forEach{i->val marks=if(i<=10)10 else 15;val words=if(i<=10)150 else 250;Card(Modifier.fillMaxWidth().padding(top=6.dp)){Column(Modifier.padding(14.dp)){Text("Q$i. Test-mode analytical question placeholder",fontWeight=FontWeight.SemiBold);Text("$marks marks • $words words")}}};Text("Actual questions verified question bank से आएँगे; demo factual questions invent नहीं करता।",style=MaterialTheme.typography.labelMedium,modifier=Modifier.padding(top=12.dp))}}
