package com.upscprep.app

import android.content.Context
import android.os.Bundle
import androidx.activity.ComponentActivity
import androidx.activity.compose.setContent
import androidx.compose.foundation.layout.*
import androidx.compose.material3.*
import androidx.compose.runtime.*
import androidx.compose.ui.Modifier
import androidx.compose.ui.unit.dp

class LauncherActivity : ComponentActivity(){override fun onCreate(savedInstanceState:Bundle?){super.onCreate(savedInstanceState);setContent{MaterialTheme{UpscAppRoot(this)}}}}
@Composable fun UpscAppRoot(context:Context){
 val prefs=remember{context.getSharedPreferences("upsc_session",Context.MODE_PRIVATE)};val saved=remember{prefs.getString("token","")?:""};var token by remember{mutableStateOf(if(saved==DemoMode.TOKEN&&!DemoMode.ENABLED)"" else saved)};var page by remember{mutableStateOf("home")};var notesExam by remember{mutableStateOf("mains")};var currentExam by remember{mutableStateOf("prelims")};var wrongExam by remember{mutableStateOf("prelims")};var practiceExam by remember{mutableStateOf("prelims")};var target by remember{mutableStateOf<StudyTarget?>(null)};var section by remember{mutableStateOf<QuestionSectionDto?>(null)};var answerQ by remember{mutableStateOf<TopicQuestionDto?>(null)}
 if(token.isBlank()){AuthScreen{t->prefs.edit().putString("token",t).apply();token=t};return};val demo=DemoMode.ENABLED&&token==DemoMode.TOKEN;fun logout(){prefs.edit().remove("token").apply();token=""}
 Scaffold(bottomBar={NavigationBar{listOf("Home","Prelims","Mains","Optional").forEach{x->NavigationBarItem(page.equals(x,true),{page=x.lowercase()},{},{Text(x)})}}}){pad->Box(Modifier.padding(pad).fillMaxSize()){when(page){
 "home"->if(demo)DemoHomeScreen({page=it},{logout()})else HomeScreen(token,{page="prelims"},{page="mains"},{page="optional"},{logout()})
 "prelims"->SimpleSection("PRELIMS",listOf("📚 पढ़ाई करें","🤖 AI Teacher","🧠 Practice","⏱ Mock Test","📜 PYQ","📰 Current Affairs","🗂 Class Notes","❌ Wrong Questions","🔄 Revision"),{x->when{x.startsWith("📚")->page="prelims_syllabus";x.startsWith("🤖")->page=if(demo)"demo_ai" else "ai_teacher";x.startsWith("🧠")->{practiceExam="prelims";page=if(demo)"demo_completed" else "completed_practice"};x.startsWith("⏱")->page="demo_mock";x.startsWith("📜")->page=if(demo)"demo_pyq" else "prelims_pyq";x.startsWith("📰")->if(demo)page="demo_current" else{currentExam="prelims";page="current_affairs"};x.startsWith("🗂")->if(demo)page="demo_notes" else{notesExam="prelims";page="class_notes"};x.startsWith("❌")->if(demo)page="demo_wrong" else{wrongExam="prelims";page="wrong_questions"};else->page="demo_revision"}},{page="home"})
 "mains"->SimpleSection("MAINS",listOf("📚 GS / Essay पढ़ें","🤖 AI Teacher","✍ Answer Writing","📄 Test / PDF Paper","📜 PYQ","📰 Mains Current Affairs","🗂 Class Notes","❌ Wrong Questions","🔄 Revision"),{x->when{x.startsWith("📚")->page="mains_syllabus";x.startsWith("🤖")->page=if(demo)"demo_ai" else "ai_teacher";x.startsWith("✍")->{practiceExam="mains";page=if(demo)"demo_completed" else "completed_practice"};x.startsWith("📄")->page="demo_mains_test";x.startsWith("📜")->page=if(demo)"demo_pyq" else "mains_pyq";x.startsWith("📰")->if(demo)page="demo_current" else{currentExam="mains";page="current_affairs"};x.startsWith("🗂")->if(demo)page="demo_notes" else{notesExam="mains";page="class_notes"};x.startsWith("❌")->if(demo)page="demo_wrong" else{wrongExam="mains";page="wrong_questions"};else->page="demo_revision"}},{page="home"})
 "optional"->if(demo)DemoOptionalScreen{page="home"}else OptionalScreen(token,{notesExam="optional";page="class_notes"}){page="home"}
 "prelims_syllabus"->if(demo)DemoSyllabusScreen("prelims","PRELIMS SYLLABUS",{target=it;page="topic_study"}){page="prelims"}else SyllabusScreen(token,"prelims","PRELIMS SYLLABUS",{r,t->target=StudyTarget("prelims",r.paper,r.subject,t);page="topic_study"}){page="prelims"}
 "mains_syllabus"->if(demo)DemoSyllabusScreen("mains","MAINS SYLLABUS",{target=it;page="topic_study"}){page="mains"}else SyllabusScreen(token,"mains","MAINS SYLLABUS",{r,t->target=StudyTarget("mains",r.paper,r.subject,t);page="topic_study"}){page="mains"}
 "topic_study"->target?.let{t->if(demo)DemoTopicStudyScreen(t,{page="demo_questions"}){page=if(t.exam=="prelims")"prelims_syllabus" else "mains_syllabus"}else TopicStudyV2Screen(token,t){page=if(t.exam=="prelims")"prelims_syllabus" else "mains_syllabus"}}
 "demo_questions"->target?.let{t->DemoQuestionScreen(t,{q->answerQ=q;page="demo_answer"}){page="topic_study"}}
 "demo_completed"->{val ts=DemoTestData.completed.mapNotNull{raw->val p=raw.split('|');if(p.size==4&&p[0]==practiceExam)StudyTarget(p[0],p[1],p[2],p[3])else null};DemoCompletedScreen(practiceExam,ts,{target=it;page="demo_questions"}){page=practiceExam}}
 "demo_ai"->DemoAiTeacherScreen{page="home"};"demo_mock"->DemoMockScreen{page="prelims"};"demo_answer"->answerQ?.let{q->MainsAnswerWritingScreen(context,DemoMode.TOKEN,q){page="demo_questions"}};"demo_mains_test"->DemoMainsPaperScreen{page="mains"};"demo_notes"->DemoNotesScreen(context){page="home"};"demo_wrong"->DemoWrongScreen{page="home"};"demo_revision"->DemoRevisionScreen{page="home"}
 "demo_pyq"->DemoOfficialOnlyScreen("PYQ","Official UPSC previous question papers production में official UPSC source से fetch/store होंगे।"){page="home"};"demo_current"->DemoOfficialOnlyScreen("Current Affairs","Daily current affairs production में verified official PIB/government/official evidence gate से date-wise आएँगे।"){page="home"}
 "prelims_pyq"->PyqScreen(token,"prelims"){page="prelims"};"mains_pyq"->PyqScreen(token,"mains"){page="mains"};"current_affairs"->CurrentAffairsScreen(token,currentExam){page=if(currentExam=="prelims")"prelims" else "mains"};"wrong_questions"->WrongQuestionsScreen(token,wrongExam){page=if(wrongExam=="prelims")"prelims" else "mains"};"class_notes"->ClassNotesScreen(context,token,notesExam){page=if(notesExam=="optional")"optional" else notesExam};"ai_teacher"->AiTeacherScreen(token){page="home"};"completed_practice"->CompletedPracticeScreen(token,practiceExam,{page=practiceExam},{section=it;page="topic_questions"});"topic_questions"->section?.let{s->TopicQuestionListScreen(token,s,{page="completed_practice"},{q->answerQ=q;page="mains_answer"})};"mains_answer"->answerQ?.let{q->MainsAnswerWritingScreen(context,token,q){page="topic_questions"}}
 }}}}
@Composable private fun DemoHomeScreen(open:(String)->Unit,logout:()->Unit){Column(Modifier.fillMaxSize().padding(20.dp)){Text("UPSC",style=MaterialTheme.typography.headlineLarge);Text("TEST MODE • Functional original-flow testing",Modifier.padding(bottom=12.dp));listOf("PRELIMS" to "prelims","MAINS" to "mains","OPTIONAL" to "optional","AI TEACHER" to "demo_ai","CURRENT AFFAIRS" to "demo_current","CLASS NOTES" to "demo_notes","PYQ" to "demo_pyq","WRONG QUESTIONS" to "demo_wrong","REVISION" to "demo_revision").forEach{(a,b)->ElevatedCard({open(b)},Modifier.fillMaxWidth().padding(vertical=4.dp)){Text(a,Modifier.padding(16.dp))}};TextButton(onClick=logout){Text("Test Mode से बाहर जाएँ")}}}
@Composable private fun DemoCompletedScreen(exam:String,targets:List<StudyTarget>,open:(StudyTarget)->Unit,back:()->Unit){Column(Modifier.fillMaxSize().padding(20.dp)){TextButton(onClick=back){Text("← ${exam.uppercase()} PRACTICE")};Text("Completed Topics",style=MaterialTheme.typography.headlineSmall);if(targets.isEmpty())Text("पहले Syllabus में topic Complete करें।",Modifier.padding(top=16.dp));targets.forEach{t->Card({open(t)},Modifier.fillMaxWidth().padding(vertical=5.dp)){Column(Modifier.padding(16.dp)){Text(t.paper);Text(t.subject);Text(t.topic)}}}}}
